### ISSUE TITLE
Crashing when punched

### ISSUE THREAD

**Issue by Borealnebula75** [BuiltBrokenModding/SBM-SheepMetal#1]
[crash-2019-05-27_14.37.17-server.txt](https://github.com/BuiltBrokenModding/SBM-SheepMetal/files/3249886/crash-2019-05-27_14.37.17-server.txt)
Do note: 2nd time the blockling was dominating the sheep, computer is extremely weak, and only happened 2nd time.
Edit (pastebin clone report):
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  ItemPatchingLoader (ItemPhysic+Lite+1.3.7+mc1.12.2.jar)
  Quark Plugin (Quark-r1.5-152.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/27/19 2:37 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.world.storage.loot.LootEntryItem.func_186363_a(LootEntryItem.java:32)
	at net.minecraft.world.storage.loot.LootPool.func_186452_a(LootPool.java:68)
	at net.minecraft.world.storage.loot.LootPool.func_186449_b(LootPool.java:83)
	at net.minecraft.world.storage.loot.LootTable.func_186462_a(LootTable.java:42)
	at net.minecraft.entity.EntityLiving.func_184610_a(EntityLiving.java:635)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1197)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1023)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at com.blocklings.entities.EntityBlockling.func_70652_k(EntityBlockling.java:272)
	at com.blocklings.entities.BlocklingAIAttackMelee.checkAndPerformAttack(BlocklingAIAttackMelee.java:217)
	at com.blocklings.entities.BlocklingAIAttackMelee.func_75246_d(BlocklingAIAttackMelee.java:202)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.blocklings.entities.EntityBlockling.func_70636_d(EntityBlockling.java:552)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.blocklings.entities.EntityBlockling.func_70071_h_(EntityBlockling.java:672)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.storage.loot.LootEntryItem.func_186363_a(LootEntryItem.java:32)
	at net.minecraft.world.storage.loot.LootPool.func_186452_a(LootPool.java:68)
	at net.minecraft.world.storage.loot.LootPool.func_186449_b(LootPool.java:83)
	at net.minecraft.world.storage.loot.LootTable.func_186462_a(LootTable.java:42)
	at net.minecraft.entity.EntityLiving.func_184610_a(EntityLiving.java:635)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1197)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1023)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at com.blocklings.entities.EntityBlockling.func_70652_k(EntityBlockling.java:272)
	at com.blocklings.entities.BlocklingAIAttackMelee.checkAndPerformAttack(BlocklingAIAttackMelee.java:217)
	at com.blocklings.entities.BlocklingAIAttackMelee.func_75246_d(BlocklingAIAttackMelee.java:202)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.blocklings.entities.EntityBlockling.func_70636_d(EntityBlockling.java:552)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.blocklings.entities.EntityBlockling.func_70071_h_(EntityBlockling.java:672)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: blocklings:entity_blockling (com.blocklings.entities.EntityBlockling)
	Entity ID: 1299
	Entity Name: Blockling
	Entity's Exact location: 97.21, 68.00, 243.40
	Entity's Block location: World: (97,68,243), Chunk: (at 1,4,3 in 6,15; contains blocks 96,0,240 to 111,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.02, -0.08, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Borealnebula75'/719, l='New World', x=99.99, y=69.00, z=242.39]]
	Chunk stats: ServerChunkCache: 341 Drop: 0
	Level seed: 2088632130647067442
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"large_zones","rainScheme":"large_zones","biomeSize":"large","amplitude":1.0,"generateBopOre":true,"generatePoisonIvy":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":false,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (124,64,256), Chunk: (at 12,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10418 game time, 10418 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 35324 (now: false), thunder time: 123840 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 756814560 bytes (721 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 107
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 91 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version                         | Source                                         | Signature                                |
	|:------ |:----------------- |:------------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2                          | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp               | 9.42                            | minecraft.jar                                  | None                                     |
	| LCHIJA | FML               | 8.0.99.99                       | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2838                    | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | itemphysic        | 1.4.0                           | minecraft.jar                                  | None                                     |
	| LCHIJA | securitycraft     | v1.8.12                         | [1.12.2]+SecurityCraft+v1.8.12.jar             | None                                     |
	| LCHIJA | organiccreepers   | 1.12.2                          | [1.12.2]OrganicCreepers-1.2.5.jar              | None                                     |
	| LCHIJA | uncraftingtable   | 1.8-beta6                       | [1.12]UncraftingTable-1.8-beta6.jar            | None                                     |
	| LCHIJA | alwaysdroploot    | 1.12.2-1.0.1                    | alwaysdroploot-1.12.2-1.0.1.jar                | None                                     |
	| LCHIJA | applecore         | 3.2.0                           | AppleCore-mc1.12.2-3.2.0.jar                   | None                                     |
	| LCHIJA | jei               | 4.15.0.268                      | jei_1.12.2-4.15.0.268.jar                      | None                                     |
	| LCHIJA | appleskin         | 1.0.9                           | AppleSkin-mc1.12-1.0.9.jar                     | None                                     |
	| LCHIJA | biomesoplenty     | 7.0.1.2439                      | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar  | None                                     |
	| LCHIJA | aqua_creepers     | 1.2.3                           | AquaCreepers-1.2.3.jar                         | None                                     |
	| LCHIJA | aquaculture       | 1.6.8                           | Aquaculture-1.12.2-1.6.8.jar                   | None                                     |
	| LCHIJA | ichunutil         | 7.2.1                           | iChunUtil-1.12.2-7.2.1.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | attachablegrinder | 7.0.0                           | AttachableGrinder-1.12.2-7.0.0.jar             | None                                     |
	| LCHIJA | quark             | r1.5-152                        | Quark-r1.5-152.jar                             | None                                     |
	| LCHIJA | autoreglib        | 1.3-29                          | AutoRegLib-1.3-29.jar                          | None                                     |
	| LCHIJA | babymobs          | 1.5.5                           | BabyMobs-1.12-1.5.5.jar                        | None                                     |
	| LCHIJA | backtools         | 7.0.0                           | BackTools-1.12.2-7.0.0.jar                     | None                                     |
	| LCHIJA | nibbler           | 0.4.1                           | nibbler-1.12.2-0.4.1.jar                       | None                                     |
	| LCHIJA | barkbooks         | 1.2                             | barkbooks-1.12.2-1.2.jar                       | None                                     |
	| LCHIJA | ic2               | 2.8.109-ex112                   | industrialcraft-2-2.8.109-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | mmdlib            | 1.0.0-rc2                       | MMDLib-1.12-1.0.0-rc2.36.jar                   | None                                     |
	| LCHIJA | basemetals        | 2.5.0-rc2                       | BaseMetals-1.12-2.5.0-rc2.332.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | golems            | 7.1.4                           | ExtraGolems-1.12-7.1.4.jar                     | None                                     |
	| LCHIJA | modernmetals      | 2.5.0-rc2                       | ModernMetals-1.12-2.5.0-rc2.152.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | golems_metal      | 7.1.1-1                         | BaseMetalGolems[1.12.2]-7.1.1-1.jar            | None                                     |
	| LCHIJA | birdsnests        | 2.1.0                           | BirdsNests1.12.2-2.1.0.jar                     | None                                     |
	| LCHIJA | blocklings        | 6.0.1                           | Blocklings+6.0.1+-+1.12.2.jar                  | None                                     |
	| LCHIJA | bullseye          | 3.0.7                           | Bullseye-1.12.2-3.0.7.jar                      | None                                     |
	| LCHIJA | cakechomps        | 1.12.2-1.0                      | cakechomps-1.12.2-1.0.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | carryon           | 1.12.1                          | CarryOn+MC1.12.2+v1.12.1.jar                   | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | ceanimals         | 1.4.1                           | ceanimals-1.12.2-1.4.1.jar                     | None                                     |
	| LCHIJA | ceramics          | 1.12-1.3.7                      | Ceramics-1.12-1.3.7.jar                        | None                                     |
	| LCHIJA | chunkanimator     | 1.2                             | ChunkAnimator-MC1.12-1.2.jar                   | None                                     |
	| LCHIJA | coloredredstone   | 1.3.2                           | Colored+Redstone-1.3.2.jar                     | None                                     |
	| LCHIJA | extendedrenderer  | v1.0                            | coroutil-1.12.1-1.2.31.jar                     | None                                     |
	| LCHIJA | coroutil          | 1.12.1-1.2.31                   | coroutil-1.12.1-1.2.31.jar                     | None                                     |
	| LCHIJA | configmod         | v1.0                            | coroutil-1.12.1-1.2.31.jar                     | None                                     |
	| LCHIJA | exhaustedstamina  | 1.2                             | exhaustedstamina-1.2.jar                       | None                                     |
	| LCHIJA | exoticbirds       | 1.0                             | Exotic+Birds+1.12.2-2.2.1.jar                  | None                                     |
	| LCHIJA | extraalchemy      | 0.3.8.6.1-release               | extraalchemy-0.3.8.6.1-release.jar             | None                                     |
	| LCHIJA | toughasnails      | 3.1.0.139                       | ToughAsNails-1.12.2-3.1.0.139-universal.jar    | None                                     |
	| LCHIJA | forestry          | 5.8.1.322                       | forestry_1.12.2-5.8.1.322.jar                  | None                                     |
	| LCHIJA | cfm               | 6.3.0                           | furniture-6.3.0-1.12.2.jar                     | None                                     |
	| LCHIJA | gravitygun        | 7.0.0                           | GravityGun-1.12.2-7.0.1.jar                    | None                                     |
	| LCHIJA | hammercore        | 2.0.4.7                         | HammerCore-1.12.2-2.0.4.7.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | headcrumbs        | 2.0.4                           | Headcrumbs-1.12.2-2.0.5.17.jar                 | None                                     |
	| LCHIJA | leatherworks      | 1.78.0                          | LeatherWorks-1.12-1.78.0.42.jar                | None                                     |
	| LCHIJA | lucky             | 7.6.0                           | luckyblock-1.12.2-7.6.0.zip                    | None                                     |
	| LCHIJA | lunatriuscore     | 1.2.0.42                        | LunatriusCore-1.12.2-1.2.0.42-universal.jar    | None                                     |
	| LCHIJA | jmcm              | 9.2                             | MinecraftCapes Forge 1.12.2.jar                | None                                     |
	| LCHIJA | testdummy         | 1.12                            | MmmMmmMmmMmm-1.12-1.14.jar                     | None                                     |
	| LCHIJA | mobamputation     | 7.0.0                           | MobAmputation-1.12.2-7.0.0.jar                 | None                                     |
	| LCHIJA | mobbattle         | 2.3.1[1.12]                     | MobBattleMod-1.12.2-2.3.1.jar                  | None                                     |
	| LCHIJA | morecharcoal      | 1.0.2                           | morecharcoal-1.0.2.jar                         | None                                     |
	| LCHIJA | guilib            | $version                        | morepaintings-paintings-1.12.2-5.0.1.1.jar     | None                                     |
	| LCHIJA | paintingselgui    | $version                        | morepaintings-paintings-1.12.2-5.0.1.1.jar     | None                                     |
	| LCHIJA | morepaintings     | $version                        | morepaintings-paintings-1.12.2-5.0.1.1.jar     | None                                     |
	| LCHIJA | morph             | 7.1.3                           | Morph-1.12.2-7.1.3.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | multimine         | 1.6.0                           | MultiMine-1.12.2.jar                           | None                                     |
	| LCHIJA | multimob          | 1.0.5                           | multimob-1.0.5.jar                             | None                                     |
	| LCHIJA | naturescompass    | 1.5.1                           | NaturesCompass-1.12.2-1.5.1.jar                | None                                     |
	| LCHIJA | orespawn          | 3.3.1                           | OreSpawn-1.12-3.3.1.172.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | primitivemobs     | 1.2.3a                          | primitivemobs-1.2.3a.jar                       | None                                     |
	| LCHIJA | pumpkincarving    | 1.4.0                           | PumpkinCarving1.12-1.4.0.jar                   | None                                     |
	| LCHIJA | realistictorches  | 2.1.1                           | RealisticTorches-1.12.2-2.1.1.jar              | None                                     |
	| LCHIJA | sbmsheepmetal     | 1.12.2-0.1.0.20190223151926     | SBM-SheepMetal-1.12.2-0.1.0b20190223151929.jar | None                                     |
	| LCHIJA | woodenshears      | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | SBM-WoodenShears-1.12-0.0.1b8.jar              | None                                     |
	| LCHIJA | schematica        | 1.8.0.169                       | Schematica-1.12.2-1.8.0.169-universal.jar      | None                                     |
	| LCHIJA | sekcphysics       | 0.1.0                           | sekcphysics-0.1.0.jar                          | None                                     |
	| LCHIJA | shouldersurfing   | 1.16                            | ShoulderSurfing-1.12.2-1.15.1.jar              | d6261bb645f41db84c74f98e512c2bb43f188af2 |
	| LCHIJA | simplewoodenpipes | 1.0.1                           | simplewoodenpipes-1.12.2-1.0.1.jar             | 075143b8d04af6213d5b5936048e9b8012eb5cec |
	| LCHIJA | skewers           | 1.1                             | Skewers-1.1.jar                                | None                                     |
	| LCHIJA | spartanshields    | 1.5.4                           | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
	| LCHIJA | spiceoflife       | 1.3.12                          | SpiceOfLife-mc1.12-1.3.12 - Copy.jar           | None                                     |
	| LCHIJA | stacksize         | 1.1                             | stacksize-1.12.2-1.0.jar                       | None                                     |
	| LCHIJA | stg               | 1.12.2-1.2.3                    | stg-1.12.2-1.2.3.jar                           | None                                     |
	| LCHIJA | strawgolem        | 1.3                             | strawgolem-1.3.jar                             | None                                     |
	| LCHIJA | torohealthmod     | 1.12.2-11                       | torohealth-1.12.2-11.jar                       | None                                     |
	| LCHIJA | venomousfangs     | 1.1                             | VenomousFangs1.12-1.1.jar                      | None                                     |
	| LCHIJA | visuals           | 6r                              | Visuals-1.12.2-6r.jar                          | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | wanionlib         | 1.12.2-2.2                      | WanionLib-1.12.2-2.2.jar                       | None                                     |
	| LCHIJA | weather2          | 1.12.1-2.6.12                   | weather2-1.12.1-2.6.12.jar                     | None                                     |
	| LCHIJA | wolfarmor         | 2.2.3.6                         | wolfarmor-1.12.2-2.2.3.1798-universal.jar      | None                                     |
	| LCHIJA | zombieawareness   | 1.12.1-1.11.16                  | zombieawareness-1.12.1-1.11.16.jar             | None                                     |
	| LCHIJA | deathmaps         | 1.0.0                           | deathmaps-1.12.2-1.0.0.jar                     | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| LCHIJA | totemexpansion    | 1.2.2                           | totemexpansion-1.2.2-1.12.2.jar                | None                                     |
	| LCHIJA | unidict           | 1.12.2-2.9.2                    | UniDict-1.12.2-2.9.2.jar                       | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
ItemPatchingLoader (ItemPhysic+Lite+1.3.7+mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
Quark Plugin (Quark-r1.5-152.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 1779 names; 2652 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Visuals (visuals) @6r

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Borealnebula75'/719, l='New World', x=99.99, y=69.00, z=242.39]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by dmodoomsirius** [comment]
please use something similar to [http://pastebin.com](http://pastebin.com )

**Comment by Tommeh1** [comment]
Did some testing and concluded the following:
-This can happen to any kind of the metal sheep
-TNT is assured to trigger it
-Even spawning them can trigger it
crash report: https://gist.github.com/CraftalotReloaded/a08308a871fd9826180b6c9ce99809ea

**Comment by DarkGuardsman** [comment]
Will be fixed in the next 1.12.2 release. Seems we were doing a JSON and event-driven registry of loot table. With the incode event-driven version passing in null for functions in the loot entry. This would cause it to randomly crash on entity death.

**Comment by Borealnebula75** [comment]
Okay, if there are any more issues with the mod that I notice I will send
it to ya'll
