### ISSUE TITLE
[1.12.2] "Race condition" results in crash with the Midnight/anything that modifies EnumCreatureType

### ISSUE THREAD

**Issue by noobanidus** [BuiltBrokenModding/SBM-SheepMetal#4]
I'm not 100% sure, but running this mod in my pack with the Midnight resulted in an interesting crash which seemed to indicate that, although the Midnight specifically executes its `EnumHelper.addCreatureType` in a static block, [this static call](https://github.com/BuiltBrokenModding/SBM-SheepMetal/blob/87d48a6ed500998e2aebf2c4d1cc15d54c14bf13/src/main/java/com/builtbroken/sheepmetal/config/ConfigSpawn.java#L45) to `getSheepBiomeSpawnList` may result in the `EnumCreatureType` enum being "finalised", as `getSpawnableList` creates a `switch` block around `EnumCreatureType`, which I believe results in `values()` being called and thus, all creature types added *after* this point are considered invalid.

It results in [the following crash](https://gist.github.com/duely/d3f81896a5c3982b68001998af2df470):

```java.lang.ArrayIndexOutOfBoundsException: 4
    at net.minecraft.world.biome.Biome.getSpawnableList(Biome.java:173)
    at com.mushroom.midnight.common.biome.surface.SurfaceBiome.<init>(SurfaceBiome.java:43)
    at com.mushroom.midnight.common.registry.ModSurfaceBiomes.onRegisterBiomes(ModSurfaceBiomes.java:36)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_655_ModSurfaceBiomes_onRegisterBiomes_Register.invoke(.dynamic)
```

From my research, this seems to indicate that the value for EnumCreatureType being passed to `getSpawnableList` wasn't contained in `values()`, implying that it's been finalised. I don't have a reference to the thread on the Minecraft Forge forums, but the thread seemed to indicate that executing a `switch` statement or calling `values()` would "lock" the enum and prevent any future additions to it; hence it would have to be added as a static block.

In this case, the `getSheepBiomeSpawnList` is being statically executed as well as Midnight's `EnumHelper.addCreatureType`. I'm not sure the specific rules for them loading, whether this is truly a race condition or not.

As you're using this as the default value, I'm not sure what the best possibility is. I usually define a public `String[]` used for the default variable, as well as a `List<String>` (or whatever type) that defaults to null as a private, `@Config.Ignore` value, as well as finally a public `getListOfXXX` method which checks if the `List<String>` is null and, if so, generates it.

I don't know whether this would work in this situation, as I'm not super up-to-date on how and when the configuration system is actually fired and what happens when you change default values, and when it's actually saved...

Anyway, a rather obscure bug for you! Hopefully the information I've provided is sufficient to come up with a solution!

**Comment by DarkGuardsman** [comment]
@bl4ckscor3 You wrote the config so can you look into this? 

https://github.com/BuiltBrokenModding/SBM-SheepMetal/commit/357528847b44042483367bc3603dab557b3e1189#diff-a759e141209ab116b4ec762eba1312cb

I want to say this is the wrong way to handle generating a biome list. As it results in a stale biome list that doesn't update with addition or removal of mods. Instead we should do a allow and ban list system that is set to ban by default with an empty array. Which would also likely solve the above issue.

**Comment by noobanidus** [comment]
Mystical World [uses a biome dictionary tag whitelist](https://github.com/MysticMods/MysticalWorld/blob/master/src/main/java/epicsquid/mysticalworld/config/ConfigManager.java#L108) which then get [converted into the relevant biomes at run-time](https://github.com/MysticMods/MysticalWorld/blob/68a590a8718a67366b29504e942c017dc537b5f7/src/main/java/epicsquid/mysticalworld/init/ModEntities.java#L59) which makes things pretty easy; you could probably adapt it to work as a blacklist as well.

**Comment by DarkGuardsman** [comment]
Its what we had in the 1.12 version of the mod. I think there was miscommunication when @bl4ckscor3 picked up the task to add the feature. Either way he or I will get around to it in a few days.... sooner if I get some freetime at work between doing merge requests for co-workers.

**Comment by bl4ckscor3** [comment]
Yeah, I don't know how I would get the default biomes of a sheep as the default value without this.

**Comment by DarkGuardsman** [comment]
You don't, leave the list empty and turn it into a ban list by default.

**Comment by bl4ckscor3** [comment]
But then the sheep would logically have to spawn in every biome _except_ the ones on the list... I don't see the point.

**Comment by noobanidus** [comment]
Part of the issue is that you're calculating this list way too early, in the static intialisation of the class, which means that you may very well be missing out on modded biomes that haven't been registered/instantiated yet.

**Comment by bl4ckscor3** [comment]
I understand the issue... I just don't understand how Dark wants to redo the feature.

**Comment by DarkGuardsman** [comment]
You would default to use the vanilla sheep list if the list is empty

**Comment by bl4ckscor3** [comment]
What do you want?!?! https://i.imgur.com/ZgKA3T7.png

**Comment by DarkGuardsman** [comment]
Effectively you don't generate the list in the configs. You leave the config empty and default as a ban list of biomes to not spawn inside. Then when you register the sheep to spawn in biomes you default to the vanilla sheep list. Removing any biome listed in the ban list. When set to an allow only you then generate a biome list from the config when you register the stuff.

In other words, move the logic out of the config. Place it in the location where we register the allowed biomes. Only generating things when we need them so we don't break the registries.

**Comment by bl4ckscor3** [comment]
I'm fairly confident that I fixed this now.
